/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: CzernO (https://sketchfab.com/czernobog)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/cheese-wedge-5167e6bba94a4c09b4d780f625bceeda
Title: cheese wedge
*/

import { useGLTF } from '@react-three/drei'

export function Cheese(props) {
  const { nodes, materials } = useGLTF('/cheese_wedge.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Object_2.geometry}
        material={materials.material_0}
        rotation={[-Math.PI / 2, 0, 0]}
      />
    </group>
  )
}

useGLTF.preload('/cheese_wedge.glb')
